export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const REDIRECT = "REDIRECT"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const SET_TOKEN = "SET_TOKEN"
export const RESET_ERRORS = "RESET_ERRORS"
export const FAILURE = "FAILURE"

export const INVALIDATE_USERS = "INVALIDATE_USERS"
export const FETCH_PROFILE = "FETCH_PROFILE"
export const FETCH_PROFILE_FULFILLED = "FETCH_PROFILE_FULFILLED"
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED"
export const FETCH_USERS = "FETCH_USERS"
export const FETCH_USERS_FULFILLED = "FETCH_USERS_FULFILLED"
export const SAVE_USER_FULFILLED = "SAVE_USER_FULFILLED"

export const FETCH_ROLES = "FETCH_ROLES"
export const FETCH_ROLES_FULFILLED = "FETCH_ROLES_FULFILLED"

export const FETCH_CART = "FETCH_CART"
export const FETCH_CART_FULFILLED = "FETCH_CART_FULFILLED"
export const FETCH_CARTS = "FETCH_CARTS"
export const FETCH_CARTS_FULFILLED = "FETCH_CARTS_FULFILLED"
export const SAVE_CART = "SAVE_CART"
export const SAVE_CART_FULFILLED = "SAVE_CART_FULFILLED"
export const SAVE_CHANGE_CUSTOMER_FULFILLED = "SAVE_CHANGE_CUSTOMER_FULFILLED"
export const CHECKOUT_CART_FULFILLED = "CHECKOUT_CART_FULFILLED"

export const INVALIDATE_CATEGORIES = "INVALIDATE_CATEGORIES"
export const FETCH_CATEGORY_FULFILLED = "FETCH_CATEGORY_FULFILLED"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED"
export const SAVE_CATEGORY_FULFILLED = "SAVE_CATEGORY_FULFILLED"

export const INVALIDATE_PRODUCTS = "INVALIDATE_PRODUCTS"
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const FETCH_PRODUCT_FULFILLED = "FETCH_PRODUCT_FULFILLED"
export const SAVE_PRODUCT = "SAVE_PRODUCT"
export const SAVE_PRODUCT_FULFILLED = "SAVE_PRODUCT_FULFILLED"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCTS_FULFILLED = "FETCH_PRODUCTS_FULFILLED"

export const FETCH_ORDERS = "FETCH_ORDERS"
export const FETCH_ORDERS_FULFILLED = "FETCH_ORDERS_FULFILLED"
export const SAVE_ORDERS_FULFILLED = "SAVE_ORDERS_FULFILLED"
export const UPDATE_ORDER_FULFILLED = "UPDATE_ORDER_FULFILLED"

export const INVALIDATE_TABLES = "INVALIDATE_TABLES"
export const FETCH_TABLE_FULFILLED = "FETCH_TABLE_FULFILLED"
export const FETCH_TABLES = "FETCH_TABLES"
export const FETCH_TABLES_FULFILLED = "FETCH_TABLES_FULFILLED"
export const SAVE_TABLE_FULFILLED = "SAVE_TABLE_FULFILLED"


export const SAVE_TRANSACTION = "SAVE_TRANSACTION"
export const SAVE_TRANSACTION_FULFILLED = "SAVE_TRANSACTION_FULFILLED"
export const SAVE_TRANSACTION_FAILED = "SAVE_TRANSACTION_FAILED"
export const FETCH_TRANSACTION = "FETCH_TRANSACTION"
export const FETCH_TRANSACTION_FULFILLED = "FETCH_TRANSACTION_FULFILLED"
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS"
export const FETCH_TRANSACTIONS_FULFILLED = "FETCH_TRANSACTIONS_FULFILLED"
export const FETCH_SALES = "FETCH_SALES"
export const FETCH_SALES_FULFILLED = "FETCH_SALES_FULFILLED"





