export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const REDIRECT = "REDIRECT"
export const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_TOKEN = "SET_TOKEN"

export const FETCH_CART = "FETCH_CART"
export const FETCH_CART_FULFILLED = "FETCH_CART_FULFILLED"
export const FETCH_CARTS = "FETCH_CARTS"
export const FETCH_CARTS_FULFILLED = "FETCH_CARTS_FULFILLED"
export const SAVE_CART = "SAVE_CART"
export const SAVE_CART_FULFILLED = "SAVE_CART_FULFILLED"
export const SAVE_CHANGE_CUSTOMER_FULFILLED = "SAVE_CHANGE_CUSTOMER_FULFILLED"
export const CHECKOUT_CART_FULFILLED = "CHECKOUT_CART_FULFILLED"

export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED"

export const FETCH_MENU = "FETCH_MENU"
export const FETCH_MENU_FULFILLED = "FETCH_MENU_FULFILLED"

export const FETCH_ORDERS = "FETCH_ORDERS"
export const FETCH_ORDERS_FULFILLED = "FETCH_ORDERS_FULFILLED"
export const SAVE_ORDERS_FULFILLED = "SAVE_ORDERS_FULFILLED"
export const UPDATE_ORDER_FULFILLED = "UPDATE_ORDER_FULFILLED"


export const FETCH_TABLES = "FETCH_TABLES"
export const FETCH_TABLES_FULFILLED = "FETCH_TABLES_FULFILLED"

export const SAVE_TRANSACTION = "SAVE_TRANSACTION"
export const SAVE_TRANSACTION_FULFILLED = "SAVE_TRANSACTION_FULFILLED"
export const SAVE_TRANSACTION_FAILED = "SAVE_TRANSACTION_FAILED"
export const FETCH_TRANSACTION = "FETCH_TRANSACTION"
export const FETCH_TRANSACTION_FULFILLED = "FETCH_TRANSACTION_FULFILLED"
export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS"
export const FETCH_TRANSACTIONS_FULFILLED = "FETCH_TRANSACTIONS_FULFILLED"





